

###

# POST http̥s://localhost:4000/auth/signup 
# Content-Type: application/json

# {
#     "email": "bhtibrewal@gmail.com",
#     "password": "bhtib@1999",
#     "name": "bhavika",
#     "username": "bhtib"
# }