GET http://localhost:4000/api/posts

###
GET http://localhost:4000/api/users


###
POST http://localhost:4000/api/auth/signup
content-type: application/json

{
    "email": "guest@gmail.com",
    "password": "guest@1234",
    "name": "Guest User",
    "username": "guest_123"
}

###
POST http://localhost:4000/api/auth/login
content-type: application/json

{
    "password": "bhtib@1999",
    "username": "bhtib"
}

###
GET http://localhost:4000/api/users/629b958210857a7381bca03a

###
POST http://localhost:4000/api/posts
content-type: application/json

{
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
}

###
DELETE http://localhost:4000/api/posts/629baed335558de24ef63e8e
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQ0NTIzOTUsImV4cCI6MTY1NTA1NzE5NX0.JNsGvIRxjUh7Vtq_BEoGeG_Y31wOE6d6nrviRj-mV4w


###
GET http://localhost:4000/api/posts/629baed335558de24ef63e8e