### get users
GET http://localhost:4000/api/users

### 
POST http://localhost:4000/api/auth/signup
content-type: application/json

{
    "email": "tanay@gmail.com",
    "password": "tanay@1234",
    "name": "Tanay Pratap",
    "username": "tanay_123"
}

### login
POST http://localhost:4000/api/auth/login
content-type: application/json

{
    "password": "guest@1234",
    "username": "guest_123"
}
### tanay_123
### get user
GET http://localhost:4000/api/users/guest_123

### update user details
PUT http://localhost:4000/api/users/guest_123
content-type: application/json

{
    "website": "artsyshop.netlify.app",
    "bio": "Hi, I am Guest User!!"
}

### follow user
POST http://localhost:4000/api/user/follow 
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliYmNkMmZhMzBlNGM3MTI1MzNkZGIiLCJpYXQiOjE2NTU1NTE0OTcsImV4cCI6MTY1NjE1NjI5N30.qQ4Wc73xTolRlp7tBbJKUwHGwpGGcjo93PuuUkDI304

{
    "followeeId": "62adb58a259012f746c6b089"
}

### create post
POST http://localhost:4000/api/posts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

{
    "content": "new content",
    
}

### get posts
GET http://localhost:4000/api/posts

###
GET http://localhost:4000/api/comments
authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NzEyMjIsImV4cCI6MTY1NTU3NjAyMn0.JRugDcYe4yHAyQwpqKGXnf1lfgJUTa-WLKx8UD7BBVw

### delete post
DELETE http://localhost:4000/api/posts/629cb4fb94470f9941ff5f5c
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

### getpost
GET http://localhost:4000/api/posts/629cb51694470f9941ff5f5e
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

### edit post
PUT  http://localhost:4000/api/posts/62af090430baa7a276e05ac2
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

{
    "image": "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435"
}

### like post
POST  http://localhost:4000/api/posts/likes/62a4f01c224e9fb940ad8901
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

### add comment
POST  http://localhost:4000/api/comments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

{ 
    "postId":"629cb51694470f9941ff5f5e",
    "body":  "this is comment"
}

###
POST http://localhost:4000/api/comments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

{
    "postId":"629cb51694470f9941ff5f5e",
    "body":  "this is reply",
    "parentId": "62a5e6b6198ec939c0791100"
}

###
DELETE  http://localhost:4000/api/comments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOTU4MjEwODU3YTczODFiY2EwM2EiLCJpYXQiOjE2NTQ5NTQxMzMsImV4cCI6MTY1NTU1ODkzM30.7AM_VzSn-ufMOngzHreqVeJ1wwTlEZwYOs9AweGiPfI

{ 
    "postId": "629cb51694470f9941ff5f5e",
    "parentCommentId": "62a5e6b6198ec939c0791100",
    "commentId": "62a5ea0e22e47f020e06d61f"
}

###
POST http://localhost:4000/api/post/bookmark
